### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by zkrige** [iteufel/nwjs-ffmpeg-prebuilt#130]
It seems this project has been abandoned. I was in talks with @iteufel last year, and he mentioned he is extremely busy.

I'm willing to take over the repo, and I have access to the actions, but the builds are failing. Is there anyone willing to help me get the builds running?

**Comment by iteufel** [comment]
Hello @zkrige for any changes and fixes I am gladly open.
Currently I have some more time again and will try to create new binaries for v0.60.0 later this week.

**Comment by zkrige** [comment]
ah awesome. Good to hear you're still around.

I cloned the repo and the linux and macOS images built, but windows failed.

I'm happy to trigger builds on your repo - just let me know what must be done

**Comment by zkrige** [comment]
I suspect the windows image is larger than what bitbucket allows - is there any way around this

**Comment by vg30** [comment]
I did not understand your question?

**Comment by zkrige** [comment]
GitHub is failing the windows build because it runs out of disk space. Is there any way to increase the disk space on the actions for windows?

**Comment by fm10000** [comment]
think you!

**Comment by zkrige** [comment]
@iteufel if we can figure out how to fix the pipeline, we can automate the builds - does anyone have any ideas on how to free up space on the windows images?

**Comment by YLivay** [comment]
hey, just ran a test on windows-latest, looks like C:\ has around 90 GB free disk space and D:\ has around 13 GB.
perhaps all we need to do is to just work on C: ?

**Comment by zkrige** [comment]
ive been doing some testing this afternoon to try get it running on C: - will report back

**Comment by zkrige** [comment]
ok - progress - I just need to figure out how to point it at the output files and we should be golden

<img width="759" alt="image" src="https://user-images.githubusercontent.com/968412/151556184-40ae74c1-6cb7-4deb-91da-2c1fa84bb90a.png">

**Comment by zkrige** [comment]
great success. I've got the builds working on C: on my personal repo. I've applied the changes here, so we should have fresh builds soon

**Comment by zkrige** [comment]
@iteufel can you elaborate on how to do a release once artifacts are uploaded

**Comment by iteufel** [comment]
@zkrige https://github.com/marvinpinto/action-automatic-releases

An example configuration that might work.
```
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: artifacts
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
          artifacts/**/*.zip
```
